spring:
  data:
    mongodb:
      port: 0 # when flapdoodle using
      database: library
  main:
    allow-bean-definition-overriding: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "ApplicationRunner" # default
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local