spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
